### ISSUE TITLE
Cannot build on EL6 after 0.5.1

### ISSUE THREAD

**Issue by esproul** [dvidelabs/flatcc#134]
At my company we use 0.4.3 currently, and are testing newer versions.  We've found that we cannot build >= 0.5.2 on EL6, due to some issue with C++ introduced in #80 .

The compile fails with many errors like:
```
error: 'INT16_C' was not declared in this scope
```
and similar for other integer macros.

This same issue seems to affect EL7 < 7.4 as well.

**Comment by esproul** [comment]
Here's a log of how I built and saw the errors.

[flatcc_issue134.txt](https://github.com/dvidelabs/flatcc/files/3887684/flatcc_issue134.txt)

**Comment by mikkelfj** [comment]
If you are only using C, the simplest short term fix is probably to comment out the offending C++ test while doing platform specific testing, and to disable FLATCC_TEST when deploying for production where you do not need to test the core code base, see `option(FLATCC_TEST "enable tests" ON)` in `CMakeList.txt`.

After writing this comment I noticed some other issues in your log, please refer to next comment.

If necessary we could add a FLATCC_NO_CPP_TEST option flag, but that would't solve your immediate problem since it won't go into a release immediately.

It is hard for me to pinpoint the problem since it does work with my tests, even on fairly old GCC versions (usually it is the latest GCC that causes problems).

Just some initial observations, not an explanation of what it is the actual problem, but it might help troubleshoot the problem:

- Generally the C++ test should pass, although apparently it does not in your environment (GCC 4.4.7).

- The test was added because C++ users kept reporting breaking changes post release. This especially because C++ has changed behaviour on key include files over different C++ versions, sometimes even retroactively. Adding the C++ has caught most of such problems before release.

The INT16_C is a macro to specify integer constants of type int16_t and is usually defined in <stdint.h>, and presumably also in <stdint> for C++. Flatcc's portably layer includes <flatcc/portable/pstdint.h> to make this include available even on old platforms (notably old MSVC). Flatcc generally allows an application to override this by including <stdint.h> or <stdint> before flatcc headers because it check if UINT8_MAX is defined before including pstdint.h.

Since the problem occurs when running a test, as opposed to a user project, this could be related to the compiler version and/or its standard library. I note that the GCC version is fairly old in the provided log. Tests are being run against several old GCC versions before release, but it might not cover the exact version used. It is also possible that the flags set for the given GCC version in the root CMakeList.txt are not fully correct.
The `ci-more` branch is being updated prior to release and runs several old GCC versions: https://travis-ci.org/dvidelabs/flatcc/builds/573086313

Maybe the problem is that pstdint.h should be included, but it isn't because the combination of flags takes a different include path, and that particular stdint version being used does not work as expected.

**Comment by mikkelfj** [comment]
In you log, I see:

`/tmp/build_esproul/flatcc/include/flatcc/portable/pstdalign.h:75:22: error: stdalign.h: No such file or directory`
This suggests that `flatcc/portable/pstdaligh.h` is not being included, which it should be in cases where `stdaligh.h` is not available.

You use GCC 4.4.7. The tests pass on GCC 4.4 on Travis Linux, I'm not sure what is different.

I think something else is going :
`/tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp/monster_reader.h: In function ‘const char* MyGame_Sample_Color_name(MyGame_Sample_Color_enum_t)’:
/tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp/monster_reader.h:60: error: a function call cannot appear in a constant-expression
`

Likely there is something wrong with the include paths which leads to spurious other error messages.

I think it might be related to the INSTALL configuration which is not used during normal tests. It is possibly that this configuration simply doesn't work with C++ for some reason.

**Comment by mikkelfj** [comment]
EDIT: more likely pstdaligh.h is being included, but it makes the wrong decision about whether to include `stdalign.h`.

This is notoriously difficult to get right because it depends on the standard library in use, and especially because C++ is all over the place - see source comments in:

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pstdalign.h

I suggest you start figuring out how to remove the stdaligh.h not found message by hacking the pstdalign.h file. If you resolve that, the other errors might go away and we can start figuring out how to introduce a proper fix to pstdaligh.h if indeed that is the problem.

**Comment by esproul** [comment]
@mikkelfj thank you for that detailed explanation. I will try to see if changes to `pstdalign.h` will help.

**Comment by mikkelfj** [comment]
I noticed that the root CMakeList.txt file does not define CMAKE_CXX_FLAGS for GCC compilers.
This is mostly warnings to make the tests more strict, but it might be signifiant if -DFLATCC_PORTABLE is not defined for GNU compilers < 4.7. I'm not sure how CMake behaves when CFLAGS are set but not CXX flags, you should be able to see more with verbose logging.

However, -DFLATCC_PORTABLE was originally intended to only be used with old compilers, but due to incompatibilities in even recent compiler and language versions, some portable files are always included. Therefore I do not think this is the problem. But worth noting nonetheless.

**Comment by esproul** [comment]
I am using the gcc that comes with RHEL/CentOS 6.x, which is 4.4.7:

```
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
```

This is how it looks when I run cpp on `pstdalign.h`:

```
$ cpp -dM include/flatcc/portable/pstdalign.h | grep -i align
#define PORTABLE_C11_ALIGNED_ALLOC 0
#define PORTABLE_C11_STDALIGN_MISSING
#define PSTDALIGN_H
#define __BIGGEST_ALIGNMENT__ 16
#define PORTABLE_POSIX_MEMALIGN 1
#define _Alignas(t) __attribute__((__aligned__(t)))
#define _Alignof(t) __alignof__(t)
#define __alignof_is_defined 1
#define aligned_alloc(alignment,size) __portable_aligned_alloc(alignment, size)
#define __aligned_alloc_is_defined 1
#define __aligned_free_is_defined 1
#define alignas _Alignas
#define alignof _Alignof
#define aligned_free(p) free(p)
#define __alignas_is_defined 1
```

Does that help?

**Comment by mikkelfj** [comment]
It is useful to see what you get from a raw cpp application, but this is not how it works through the build system.

We need to figure out of pstdalign.h is call through the ordinary build. This can be detected by inserting an `#error "I was here"` early in the file.

Next we need to figure out which line attempts to include <stdaligh.h>, if indeed it happens via `pstdaligh.h`.

From you dump, I notice: `PORTABLE_C11_STDALIGN_MISSING` is defined, which should prevent the inclusion of `<stdalign.h>`. The question is then why this does not happen in the ordinary build.

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/include/flatcc/portable/pstdalign.h#L97-L101

Could you try to add `-D FLATCC_PORTABLE` to CMAKE_CXX_FLAGS if pstdint.h is not included?

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/CMakeLists.txt#L191-L196

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/CMakeLists.txt#L260-L262

**Comment by mikkelfj** [comment]
For what it is worth, the dump you provided does appear to be doing the right thing for the given compiler version.

**Comment by esproul** [comment]
> I'm not sure how CMake behaves when CFLAGS are set but not CXX flags, you should be able to see more with verbose logging.

I did `make VERBOSE=1` after the cmake step, instead of the `make install` I did before. Attached is the output from where the error is first shown.

[flatcc_verbose.txt](https://github.com/dvidelabs/flatcc/files/3888595/flatcc_verbose.txt)

**Comment by esproul** [comment]
Adding `-DFLATCC_PORTABLE` to `CMAKE_CXX_FLAGS` does not seem to help:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1bb620b..00e7b2a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -259,6 +259,7 @@ endif()

 if (FLATCC_PORTABLE)
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DFLATCC_PORTABLE")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DFLATCC_PORTABLE")
 endif()

 if (CLANG_VERSION)
```

I can see that this flag is set but the error remains:

```
[ 33%] Building CXX object test/monster_test_cpp/CMakeFiles/monster_test_cpp.dir/monster_test.cpp.o
cd /tmp/build_esproul/flatcc/build/install/test/monster_test_cpp && /usr/bin/c++   -I/tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp -I/tmp/build_esproul/flatcc/include  -DFLATCC_PORTABLE -O3 -DNDEBUG   -o CMakeFiles/monster_test_cpp.dir/monster_test.cpp.o -c /tmp/build_esproul/flatcc/test/monster_test_cpp/monster_test.cpp
In file included from /tmp/build_esproul/flatcc/include/flatcc/portable/portable_basic.h:17,
                 from /tmp/build_esproul/flatcc/include/flatcc/flatcc_portable.h:8,
                 from /tmp/build_esproul/flatcc/include/flatcc/flatcc_flatbuffers.h:20,
                 from /tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp/flatbuffers_common_reader.h:9,
                 from /tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp/monster_reader.h:7,
                 from /tmp/build_esproul/flatcc/build/install/test/monster_test_cpp/generated/monster_test_cpp/monster_builder.h:7,
                 from /tmp/build_esproul/flatcc/test/monster_test_cpp/../../samples/monster/monster.c:12,
                 from /tmp/build_esproul/flatcc/test/monster_test_cpp/monster_test.cpp:2:
/tmp/build_esproul/flatcc/include/flatcc/portable/pstdalign.h:75:22: error: stdalign.h: No such file or directory
```

**Comment by mikkelfj** [comment]
It does seem to define FLATCC_PORTABLE according to your verbose dump (I'm not sure how these CMAKE flags work exactly), but anyway, that is not our worry then.

Master branch you build from fails

/tmp/build_esproul/flatcc/include/flatcc/portable/pstdalign.h:75:22: error: stdalign.h: No such file or directory

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/include/flatcc/portable/pstdalign.h#L75

Here it seems to include stdalign.h always if included from a C++ source.
I'm not sure if this is correct. GCC does not support stdalign.h before 4.7 but that might be C only.

The dump you made when calling ` cpp -dM include/flatcc/portable/pstdalign.h | grep -i align` does not tell if there is an include error.

If you comment out the include statement on line 75, does it then build?

It's risky to change pstdaligh.h for C++ because it can all sorts of side effects. I wonder why the standard tests work for GCC 4.4 but not 4.4.7 in your case. It might be the glibc version?

**Comment by esproul** [comment]
If I comment out that line, we no longer get the include error but we still get a lot of the "function call cannot appear in a constant-expression" and integer-macro undeclared in scope issues.

[make_verbose_no_stdalign.txt](https://github.com/dvidelabs/flatcc/files/3888882/make_verbose_no_stdalign.txt)

**Comment by esproul** [comment]
There is no `stdalign.h` on this system. On RHEL/CentOS 7 they have gcc-4.8.2 and it has it in a private/internal path, which is consistent with gcc having added that in 4.7.

I suppose it could come down to glibc differences.  The last release of EL6 has glibc 2.12.  Your gcc 4.4 tests seem to run on Ubuntu Trusty (14.04 LTS) which has glibc 2.19.  However, neither `libc6-dev` or `gcc-4.4` deliver a `stdalign.h` on that platform either, so that still doesn't explain how your CI could be passing.

**Comment by mikkelfj** [comment]
Yeah, agreed, that is a mystery.

pstdalign.h assumes C++ (except MSVC) provides stdalign.h for all versions. It is only C where it attempts to be GCC version specific.

On your new dump: I think these errors are because flatcc constants are defined as UINT8_C(value) and because UINT8_C (and friends) is not known to the compiler for some reason, it thinks that they are functions. That leads to a host of strange error messages.

The real question is then, why is UINT8_C, UINT32_C etc, not defined? Are these missing from early stdint.h files, or is stdint.h not included in the project for some odd reason?

**Comment by mikkelfj** [comment]
Perhaps the C++ compiler on the system defaults to a specific std=C++ version, and that version differs from my CI system?

**Comment by mikkelfj** [comment]
I got something

https://travis-ci.org/dvidelabs/flatcc/jobs/573086322
```
56.42s$ scripts/test.sh
cleaning build before tests ...
removing build products
building before tests ...
initializing build for CMake Unix Makefiles
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.8.4
```

This means to C++ compiler is more recent on Travis. That would explain the discrepancy. This means C++ 4.4.7 probably doesn't work, it just hasn't been tested.

I can fix that in pstdalign.h but it still doesn't explain the stdint.h issue. Alternatively, the C++ test should just be disabled for old C++ compilers since it is not a primary target for FlatCC.

**Comment by mikkelfj** [comment]
Related issue here: https://github.com/pytorch/pytorch/issues/23482

**Comment by mikkelfj** [comment]
The workaround seems to be `#include <stdint-gcc.h>` but I can't have that all over the place.

Can you check if pstdint.h is included instead of <stdint.h> directly? I cannot make changes to <pstdint.h> directly since it is maintained elsewhere, but I can make sure it is included if it isn't, or upgrade the version and/or request an upstream change. (If we really bother with this old C++ version).

Does it work for you if you complete disable the C++ test?

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/test/CMakeLists.txt#L5

**Comment by esproul** [comment]
> I can fix that in pstdalign.h but it still doesn't explain the stdint.h issue. Alternatively, the C++ test should just be disabled for old C++ compilers since it is not a primary target for FlatCC.

I would be fine with that.  Our usage is mostly C, and where it gets used in C++ is only on more recent distros like EL7 and Ubuntu 16.04+.

**Comment by esproul** [comment]
Yes, it works with this change:

```
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -2,7 +2,7 @@
 # Under git such files are protected with the `.gitattributes` file.
 # Incorrect line endings may lead to failed tests.
 if (FLATCC_TEST)
-add_subdirectory(monster_test_cpp)
+#add_subdirectory(monster_test_cpp)
 add_subdirectory(cgen_test)
 add_subdirectory(monster_test)
 add_subdirectory(monster_test_solo)
```

**Comment by mikkelfj** [comment]
Great, I'm going to add a FLATCC_CPP_TEST around that line, and flag it out if the C compiler is pre 4.7 GCC (don't bother check the C++ version). This won't help you with a released version, but as mentioned you can flag out the tests entirely.

**Comment by esproul** [comment]
Excellent, thank you!  We can probably test 0.6.0 with a patch that disables the test.

**Comment by mikkelfj** [comment]
Please try master @ b5e3cd9 - I just tested it locally on MacOS and did not mess with build options.

**Comment by mikkelfj** [comment]
Just to summarise the findings on this issue: stdint.g and stdalign.h is broken when C++ code includes flatcc C code and headers with GCC < 4.7. This could be fixed but is not considered worthwhile. Instead C++ test is disabled and addtionally controlled with a new build option FLATCC_CPP_TEST.

flatcc/portable/pstdalign.h handles GCC < 4.7 for gcc, but not for g++ because it assumes all C++ (except MSVC) has stdint.h. This breaks g++ 4.4.7 as reported in the original post. CI tests did pass for GCC 4.4 but only because Travis used a different g++ version at 4.8+.

Additionally stdint.h does for g++ 4.4.7 (and associated glibc) does not define UINT8_C, UINT16_C etc. macros. This does work for C via pstdint.h, but not attempt has been made to make this work when source is included via C++.

**Comment by mikkelfj** [comment]
Renamed build option to FLATCC_CXX_TEST in 8404d66  because CMAKE uses CXX.

**Comment by esproul** [comment]
Confirmed master @ ca6e33a works on my EL6 system. Thanks again!

**Comment by mikkelfj** [comment]
Thanks for confirming!
